### ISSUE TITLE
Child is_valid serializer does not update validated_data

### ISSUE THREAD

**Issue by Arinzeokeke** [apirobot/django-rest-polymorphic#16]
In Normal DRF behaviour, values can be modified, updated and returned in the validate() method, this doesn't update with PolymorphicSerializer as validated_data isn't updated to match the child serializer

**Comment by iglosiggio** [comment]
I think the simplest solution is to write a `run_validation` implementation  that makes the dispatch required.

This is my workaround implementation:
```python
def run_validation(self, data=empty):
    resource_type = self._get_resource_type_from_mapping(data)
    serializer = self._get_serializer_from_resource_type(resource_type)
    validated_data = serializer.run_validation(data)
    validated_data[self.resource_type_field_name] = resource_type
    return validated_data
```
